name: CI

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install Qt IFW
        run: |
          pip install aqtinstall
        
        
     