name: CI

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install aqtinstall
        run: |
          pip install aqtinstall

      - name: Install Qt IFW
        run: |
          python -m aqt tool windows tools_ifw 3.2.2 qt.tools.ifw.32

      - name: run QT IFW
        run: |
          cd src/RhinoPlugin
          ..\..\Tools\QtInstallerFramework\3.2\bin\binarycreator.exe -c config\config.xml -p packages YourInstaller.exe
          dir
        shell: cmd
        
     